### ISSUE TITLE
Example project won't run

### ISSUE THREAD

**Issue by schayes04** [teambition/RRuleSwift#1]
RRuleSwiftExample throws an error when attempting to run. The error is: `error: /Users/hongxin/Library/Developer/Xcode/DerivedData/RRuleSwift-bsfdvctfhfasceecxzjeffpridns/Build/Products/Debug-iphonesimulator/RRuleSwift.framework: No such file or directory`

The RRuleSwift.framework is red in the project settings when checked out:

<img width="259" alt="screen shot 2016-05-01 at 9 48 59 pm" src="https://cloud.githubusercontent.com/assets/4382161/14945818/8d94db10-0fe6-11e6-859e-63790141ee99.png">

**Comment by hongxinhope** [comment]
@schayes04 Before running the example project, you should build the framework with ```Generic iOS Device``` at first.

**Comment by schayes04** [comment]
@hongxinhope is there a way around this? Or maybe this step should be added to the README?

**Comment by simonbromberg** [comment]
This is not in the Readme anymore. Can't seem to figure out how to get the example project to run.
